name: ubuntu 16.04

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run:  cmake .
    - name: build
      run:  cmake --build .
    - name: ctest
      run:  ctest
