name: codecov

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run:  cmake -D CMAKE_BUILD_TYPE=Debug .
    - name: build
      run:  cmake --build .
    - name: test
      run:  ctest
    - name: gcov skip_amp
      run:  gcov CMakeFiles/skip_amp_test.dir/skip_amp_test.c.gcda
    - name: gcov skip_eq
      run:  gcov CMakeFiles/skip_eq_test.dir/skip_eq_test.c.gcda
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: 37cf2e5f-e870-432d-98f6-0067caed4a04
